# Generated by Django 4.2.10 on 2024-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='Без категории', max_length=100),
        ),
    ]
