# Generated by Django 4.2.10 on 2024-03-10 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
